In [2]:
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import pandas as pd

PCA : Combina os atributos

In [3]:
dataset = pd.read_csv(r'C:\Users\Edno\Desktop\Work\ALANA\PPSO-master\ransomware.csv')

In [4]:
dataset

,1,2,3,4,6,8,9,10,11,12,...,29079,29218,29287,29758,29769,29770,29796,29903,30200,30285
0,20646,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,1
1,20804,0,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,10979,1,4,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,20725,0,0,1,1,1,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,20400,0,0,0,1,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1519,11173,1,4,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,1
1520,20370,0,0,1,1,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
1521,20792,0,0,1,1,1,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
1522,10269,1,4,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
1523,20176,0,0,1,1,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0

In [5]:
train_row, teste_row = 600,600
columns = 50

tipo = dataset.iloc[:train_row, 1]
dados = dataset.iloc[:train_row, 3:columns+3]

tipo_teste = dataset.iloc[teste_row:, 1].reset_index(drop=True)
dados_teste = dataset.iloc[teste_row:, 3:columns+3].reset_index(drop=True)

In [6]:
pca = PCA(n_components=15)

In [7]:
X_treinamento_pca = pca.fit_transform(dados.values)
X_testes_pca = pca.transform(dados_teste.values)

In [8]:
X_treinamento_pca.shape, X_testes_pca.shape

((600, 15), (924, 15))

In [9]:
#ExplicaÃ§Ã£o das variÃ¡veis principais
pca.explained_variance_ratio_
pca.explained_variance_ratio_.sum()

0.8258699770514581

In [10]:
X_treinamento_pca = pd.DataFrame(X_treinamento_pca)
X_testes_pca = pd.DataFrame(X_testes_pca)

In [11]:
X_treinamento_pca

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,-1.850207,0.295986,-0.282222,0.088091,-0.334086,-0.147032,0.294623,-0.069838,-0.036301,-0.017113,-0.091469,0.103155,-0.042725,0.018788,-0.051411
1,-1.193800,-0.049386,-0.029609,-0.311075,-0.074343,-0.316941,0.397060,0.098954,0.647993,0.123018,-0.280030,-0.081915,0.027368,-0.125596,0.274907
2,-1.850207,0.295986,-0.282222,0.088091,-0.334086,-0.147032,0.294623,-0.069838,-0.036301,-0.017113,-0.091469,0.103155,-0.042725,0.018788,-0.051411
3,1.608948,-0.973994,-0.113393,-0.439104,0.003071,-0.238806,0.367039,-0.323934,-0.358399,0.393573,-0.042708,0.645103,0.122996,0.076490,0.270982
4,0.879894,0.788892,0.001369,0.435304,0.682622,-0.076701,-0.101700,-0.030847,0.458268,0.920934,0.490129,-0.032079,0.264879,0.064776,0.021311
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,1.749064,-0.615680,-0.778219,-0.683188,-0.363328,-0.360899,0.074364,-0.002500,-0.246300,0.044301,-0.027847,0.163642,-0.203359,-0.116789,0.000177
596,-1.850207,0.295986,-0.282222,0.088091,-0.334086,-0.147032,0.294623,-0.069838,-0.036301,-0.017113,-0.091469,0.103155,-0.042725,0.018788,-0.051411
597,-0.045944,-0.356479,-0.076851,-1.082642,0.030118,-0.556538,-0.512795,0.181518,0.584007,0.400819,-0.061263,-0.515352,0.481133,-0.088541,0.432412
598,0.344761,0.234516,-0.262169,-0.130031,-0.344713,0.672723,0.241976,0.132585,0.372789,0.099983,0.771789,-0.380454,0.044671,0.253471,0.345379
599,-0.905965,-0.066420,-0.215844,-0.053845,0.618944,0.584653,-0.506377,-0.155253,-0.068185,0.033591,-0.042063,-0.041953,-0.117825,-0.093362,0.225532

LDA

In [12]:
lda = LinearDiscriminantAnalysis(n_components = 8)

In [13]:
X_treinamento_lda = lda.fit_transform(dados.values, tipo.values)
X_testes_lda = lda.transform(dados_teste.values)

In [14]:
X_treinamento_lda.shape

(600, 1)